version: "3.7"

services:
  database_relatorios:
    image: postgres
    container_name: database_relatorios
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=johnny
      - POSTGRES_PASSWORD=marquinhos
      - POSTGRES_DB=relatorios
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: relatorios-ad-server
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_relatorios
    depends_on:
      - database_relatorios


volumes:
  pgdata:
    driver: local